# Generated by Django 5.2.4 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, help_text='Monthly budget cap for this category (0 = no limit / income)', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; type determines direction', max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI / Digital Wallet'), ('other', 'Other')], default='credit_card', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='spending.category')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='spending_tr_date_fa3eb2_idx'), models.Index(fields=['type'], name='spending_tr_type_8ba43e_idx'), models.Index(fields=['category', 'date'], name='spending_tr_categor_038b77_idx')],
            },
        ),
    ]
