# Generated by Django 5.2.4 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Financials', 'Financials'), ('Energy', 'Energy'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Industrials', 'Industrials'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate'), ('Materials', 'Materials'), ('Communication Services', 'Communication Services')], max_length=40)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stock_trends.stock')),
            ],
            options={
                'ordering': ['stock', 'date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='stock_trend_stock_i_fdf7c4_idx'), models.Index(fields=['date'], name='stock_trend_date_de1cf0_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
