# Generated by Django 5.2.4 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employment_length', models.PositiveIntegerField(help_text='Years employed')),
                ('credit_score', models.PositiveIntegerField(help_text='FICO-style score 300–850')),
                ('dti_ratio', models.DecimalField(decimal_places=2, help_text='Debt-to-income ratio as a percentage', max_digits=5)),
                ('home_ownership', models.CharField(choices=[('RENT', 'Rent'), ('OWN', 'Own'), ('MORTGAGE', 'Mortgage'), ('OTHER', 'Other')], default='RENT', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['credit_score'], name='loan_risk_b_credit__d08dab_idx'), models.Index(fields=['dti_ratio'], name='loan_risk_b_dti_rat_01f67a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('purpose', models.CharField(choices=[('debt_consolidation', 'Debt Consolidation'), ('home_improvement', 'Home Improvement'), ('medical', 'Medical'), ('small_business', 'Small Business'), ('education', 'Education'), ('major_purchase', 'Major Purchase'), ('car', 'Car'), ('other', 'Other')], max_length=30)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('current', 'Current'), ('paid', 'Paid'), ('default', 'Default')], default='current', max_length=10)),
                ('risk_segment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='', max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loan_risk.borrower')),
            ],
            options={
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['status'], name='loan_risk_l_status_9ab4c6_idx'), models.Index(fields=['risk_segment'], name='loan_risk_l_risk_se_3ccffc_idx'), models.Index(fields=['purpose'], name='loan_risk_l_purpose_3f585a_idx')],
            },
        ),
    ]
